// Generated by CoffeeScript 1.4.0
var getRootUri, init, message, messagesCount, onBidClick, onCloseClick, onSubmit, output, sendMessage, ws, wsUri,
  _this = this;

getRootUri = function() {
  return "ws://" + (document.location.hostname === "" ? "localhost" : document.location.hostname) + ":" + (document.location.port === "" ? "8080" : document.location.port);
};

wsUri = getRootUri() + "/websockets-stock-push/stock-generator";

message = {};

ws = {};

messagesCount = 0;

init = function() {
  if (window.WebSocket) {
    ws = new WebSocket(wsUri);
    ws.onopen = function() {
      return output("The client WebSocket.onopen was invoked");
    };
    ws.onmessage = function(e) {
      messagesCount++;
      message = JSON.parse(e.data);
      return output("Symbol: " + message.symbol + " Price: " + message.price + " Size of message payload: " + e.data.length + " bytes. Messages count: " + messagesCount);
    };
    ws.onclose = function() {
      return output("The client WebSocket.onclose was invoked");
    };
    return ws.onerror = function() {
      return output("in JavaScript function onerror");
    };
  } else {
    return output("Your browser doesn't support WebSockets :(");
  }
};

onSubmit = function() {
  var priceAndDiscount;
  priceAndDiscount = ".";
  ws.send(".");
  return output(" ");
};

onCloseClick = function() {
  return ws.close();
};

output = function(str) {
  var escaped, log;
  log = document.getElementById("log");
  escaped = str.replace(/&/, "&amp;").replace(/</, "&lt;").replace(/>/, "&gt;").replace(/"/, "&quot;");
  return log.innerHTML = escaped;
};

onBidClick = function() {
  sendMessage(message);
};

sendMessage = function(message) {
  if (ws.readyState === 1) {
    ws.send(JSON.stringify(message));
  } else {
    return console.log("offline");
  }
};
